name: Unit tests

on: push

jobs:
  unit-test:
    name: Unit tests for my API
    runs-on: ubuntu-latest

    steps:
      - name: Checkout git repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Node.js dependencies
        run: yarn ci

      - name: Revert changes in the yarn.lock file if they exists
        run: git restore yarn.lock

      - name: Run unit tests
        run: yarn run test:unit:ci
